<a href="https://colab.research.google.com/github/yuzxin/Capstone/blob/main/ASOS_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd

In [19]:
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv(
    '/content/drive/MyDrive/캡스톤_오데양/소스데이터셋/사용데이터(원본데이터)/OBS_ASOS_DD_mean_min_max.csv',
    encoding='cp949'
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
print("=== 원본 데이터 정보 ===")
print(df.info())
print(df.head())

=== 원본 데이터 정보 ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348749 entries, 0 to 348748
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   지점        348749 non-null  int64
 1   지점명       348749 non-null  object
 2   일시        348749 non-null  object
 3   평균기온(°C)  348373 non-null  float64
 4   최저기온(°C)  348716 non-null  float64
 5   최고기온(°C)  348722 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 16.0+ MB
None
   지점 지점명          일시  평균기온(°C)  최저기온(°C)  최고기온(°C)
0  90  속초  2016-01-01       3.6      -2.3       7.6
1  90  속초  2016-01-02       8.4       5.0      11.5
2  90  속초  2016-01-03       6.7       2.4       9.8
3  90  속초  2016-01-04       5.4       0.8       9.0
4  90  속초  2016-01-05       0.6      -2.6       4.4

### 데이터 파일 불러오기

In [26]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = "/content/drive/MyDrive/캡스톤_오데양/소스데이터셋/사용데이터(원본데이터)/OBS_ASOS_DD_mean_min_max.csv"

df = pd.read_csv(file_path, encoding="cp949")

df.columns = [
    "station_id",# 지점(관측소ID)
    "location",  # 지점명(관측소명)
    "date",  # 일시(관측일자)
    "temp_avg",  # 평균기온
    "temp_min",  # 최저기온
    "temp_max",  # 최고기온
]

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

   station_id location        date  temp_avg  temp_min  temp_max
0          90       속초  2016-01-01       3.6      -2.3       7.6
1          90       속초  2016-01-02       8.4       5.0      11.5
2          90       속초  2016-01-03       6.7       2.4       9.8
3          90       속초  2016-01-04       5.4       0.8       9.0
4          90       속초  2016-01-05       0.6      -2.6       4.4

### 날짜 데이터 형식 변환 (시계열)

In [28]:
# 1. 문자열 상태인 '일시' 컬럼을 판다스 날짜 객체(datetime)로 변환
df["date"] = pd.to_datetime(df["date"])

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_year"] = df["date"].dt.dayofyear

df[["date", "year", "month", "day", "day_of_year"]].head()

        date  year  month  day  day_of_year
0 2016-01-01  2016      1    1            1
1 2016-01-02  2016      1    2            2
2 2016-01-03  2016      1    3            3
3 2016-01-04  2016      1    4            4
4 2016-01-05  2016      1    5            5

### 결측치 탐지 및 시계열 보정

In [29]:
# 1. 전처리 전 컬럼별 결측치(NaN) 개수 확인 출력
print("--- 전처리 전 빈 데이터 개수 ---")
print(df.isnull().sum())

# 2. 기후 흐름을 깨지 않도록 '지점별(Location)'로 묶은 후, 비어있는 기온을 '직전 날짜 기온(ffill)'으로 1차 보정
df["temp_avg"] = df.groupby("location")["temp_avg"].ffill()
df["temp_min"] = df.groupby("location")["temp_min"].ffill()
df["temp_max"] = df.groupby("location")["temp_max"].ffill()

# 3. 만약 첫날부터 데이터가 비어있어 안 채워진 경우 '바로 다음 날 기온(bfill)'으로 2차 보정
df["temp_avg"] = df.groupby("location")["temp_avg"].bfill()
df["temp_min"] = df.groupby("location")["temp_min"].bfill()
df["temp_max"] = df.groupby("location")["temp_max"].bfill()

print("\n--- 전처리 후 빈 데이터 개수 (모두 0이어야 함) ---")
print(df.isnull().sum())

--- 전처리 전 빈 데이터 개수 ---
station_id       0
location         0
date             0
temp_avg       376
temp_min        33
temp_max        27
year             0
month            0
day              0
day_of_year      0
dtype: int64

--- 전처리 후 빈 데이터 개수 (모두 0이어야 함) ---
station_id     0
location       0
date           0
temp_avg       0
temp_min       0
temp_max       0
year           0
month          0
day            0
day_of_year    0
dtype: int64

### 데이터 논리 오류 정제 (기온 모순 데이터 이상치 필터링)

In [30]:
# 1. 논리적으로 말이 안 되는 이상치 데이터가 몇 건이나 있는지 확인
invalid_rows = df[df["temp_min"] > df["temp_max"]]
print(f"물리적 기온 오류 데이터 개수: {len(invalid_rows)}건")

물리적 기온 오류 데이터 개수: 0건

In [31]:
# 2. 최저기온이 최고기온보다 같거나 낮은 정상적인 데이터만 남기고 필터링
df = df[df["temp_min"] <= df["temp_max"]]
print(f"이상치 정제 후 남은 총 데이터 개수: {len(df):,}건")

이상치 정제 후 남은 총 데이터 개수: 348,749건

### 분석용 파생 변수 생성 (일교차 및 적산온도)

In [32]:
# 1. 일교차 생성 (최고기온 - 최저기온)
# 일교차 컬럼명 = Temp_Range
df["temp_range"] = df["temp_max"] - df["temp_min"]

In [33]:
# ================================
# 밀원수 개화용 적산온도(GDD) 계산
# 기준온도(Base Temperature) = 5℃
# ================================

BASE_TEMP = 5

# 날짜순 정렬
df = df.sort_values(["location", "date"]).reset_index(drop=True)

# 연도 생성
df["year"] = df["date"].dt.year

# 일별 GDD 계산
df["daily_gdd"] = np.maximum(0, df["temp_avg"] - BASE_TEMP)

# 연도별·지점별 적산온도 계산
df["accumulated_temp"] = (
    df.groupby(["location", "year"])["daily_gdd"]
      .cumsum()
)

# 결과 확인
display(
    df[
        [
            "location",
            "date",
            "temp_min",
            "temp_max",
            "daily_gdd",
            "accumulated_temp",
        ]
    ].head()
)

  location       date  temp_min  temp_max  daily_gdd  accumulated_temp
0       강릉 2016-01-01       2.1       8.9        0.1               0.1
1       강릉 2016-01-02       5.5      11.2        4.1               4.2
2       강릉 2016-01-03       5.3      13.8        4.0               8.2
3       강릉 2016-01-04       3.3      12.0        2.4              10.6
4       강릉 2016-01-05       0.4       7.7        0.0              10.6

###아까시나무 개화일 계산식

In [38]:
flower = (
    df[df["accumulated_temp"] >= 200]
      .groupby(["location", "year"])
      .first()
      .reset_index()
)

display(
    flower[
        [
            "location",
            "year",
            "date",
            "accumulated_temp",
        ]
    ]
)

    location  year       date  accumulated_temp
0         강릉  2016 2016-04-09             209.1
1         강릉  2017 2017-04-12             203.4
2         강릉  2018 2018-04-03             211.5
3         강릉  2019 2019-04-12             201.9
4         강릉  2020 2020-04-04             201.9
..       ...   ...        ...               ...
952      흑산도  2021 2021-03-27             202.9
953      흑산도  2022 2022-04-16             203.4
954      흑산도  2023 2023-04-11             207.4
955      흑산도  2024 2024-04-05             205.8
956      흑산도  2025 2025-04-11             203.2

[957 rows x 4 columns]

In [39]:
df.head()

,station_id,location,date,temp_avg,temp_min,temp_max,year,month,day,day_of_year,temp_range,daily_gdd,accumulated_temp
0,105,강릉,2016-01-01,5.1,2.1,8.9,2016,1,1,1,6.8,0.1,0.1
1,105,강릉,2016-01-02,9.1,5.5,11.2,2016,1,2,2,5.7,4.1,4.2
2,105,강릉,2016-01-03,9.0,5.3,13.8,2016,1,3,3,8.5,4.0,8.2
3,105,강릉,2016-01-04,7.4,3.3,12.0,2016,1,4,4,8.7,2.4,10.6
4,105,강릉,2016-01-05,3.0,0.4,7.7,2016,1,5,5,7.3,0.0,10.6

### 정제된 마스터 파일 내보내기

In [40]:
# 1. 전처리가 완료된 데이터프레임의 최종 요약 정보 확인
print("--- 전처리 완료 데이터 구조 최종 확인 ---")
print(df.info())

# 2. 깨끗해진 데이터를 'ASOS_data.csv' 파일로 저장 (인코딩 보정 포함)
output_file = "ASOS_data.csv"
df.to_csv(output_file, index=False, encoding="utf-8-sig")

print(
    f"\n 전처리가 완료되어 파일이 '{output_file}'(으)로 보관됨"
)

--- 전처리 완료 데이터 구조 최종 확인 ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348749 entries, 0 to 348748
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   station_id        348749 non-null  int64
 1   location          348749 non-null  object
 2   date              348749 non-null  datetime64[ns]
 3   temp_avg          348749 non-null  float64
 4   temp_min          348749 non-null  float64
 5   temp_max          348749 non-null  float64
 6   year              348749 non-null  int32
 7   month             348749 non-null  int32
 8   day               348749 non-null  int32
 9   day_of_year       348749 non-null  int32
 10  temp_range        348749 non-null  float64
 11  daily_gdd         348749 non-null  float64
 12  accumulated_temp  348749 non-null  float64
dtypes: datetime64[ns](1), float64(6), int32(4), int64(1), object(1)
memory usage: 29.3+ MB
None

 전처리가 완료되어 파일이 'ASOS_data.csv'(으)로 보관됨