<a href="https://colab.research.google.com/github/yuzxin/Capstone/blob/main/%EB%B0%80%EC%9B%90%EC%88%98%EC%9E%84%EC%83%81%EB%8F%84_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 산림청 - 전국 밀원수 임상도 데이터셋 전처리 코드

In [ ]:
import matplotlib.pyplot as plt

# 한글 폰트 설정
!sudo apt-get -qq install fonts-nanum

import matplotlib.font_manager as fm

font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)

plt.rc("font", family="NanumGothic")
plt.rcParams["axes.unicode_minus"] = False

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...

In [ ]:
import pandas as pd
import glob

# 1. 파일 불러오기
files = glob.glob('/content/drive/MyDrive/캡스톤/임상도소스데이터/*_loc.csv')  # 업로드 위치에 맞게 수정

df_list = []
for f in files:
    df = pd.read_csv(f, encoding='cp949', low_memory=False)
    df_list.append(df)

df = pd.concat(df_list, ignore_index=True)

print("전체 데이터:", df.shape)

전체 데이터: (3549590, 26)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3549590 entries, 0 to 3549589
Data columns (total 26 columns):
 #   Column      Dtype
---  ------      -----
 0   STORUNST    int64
 1   FROR_CD     int64
 2   FRTP_CD     int64
 3   KOFTR_GROU  int64
 4   DMCLS_CD    float64
 5   AGCLS_CD    float64
 6   DNST_CD     object
 7   HEIGHT      float64
 8   LDMARK_STN  object
 9   MAP_LABEL   object
 10  媛깆떊?꾨룄      float64
 11  ETC_PCMTT   object
 12  FRTP_NM     object
 13  KOFTR_NM    object
 14  DMCLS_NM    object
 15  AGCLS_NM    object
 16  DNST_NM     object
 17  HEIGHT_NM   object
 18  Shape_Leng  float64
 19  Shape_Area  float64
 20  EMD_CD      object
 21  EMD_NM      object
 22  layer       object
 23  path        object
 24  갱신년도        float64
 25  Shape_Le_1  float64
dtypes: float64(8), int64(4), object(14)
memory usage: 704.1+ MB

In [ ]:
df.head()

,STORUNST,FROR_CD,FRTP_CD,KOFTR_GROU,DMCLS_CD,AGCLS_CD,DNST_CD,HEIGHT,LDMARK_STN,MAP_LABEL,...,DNST_NM,HEIGHT_NM,Shape_Leng,Shape_Area,EMD_CD,EMD_NM,layer,path,갱신년도,Shape_Le_1
0,1,2,3,77,2.0,4.0,C,14.0,J12377,NMM-24C,...,밀,임분고 13m 이상 15m미만,869.285325,26490.314701,11110103.0,궁정동,NaN,NaN,NaN,NaN
1,1,2,1,11,2.0,4.0,C,30.0,J12111,NPD-24C,...,밀,임분고 29m 이상 31m미만,4873.647473,112263.952659,11110185.0,홍지동,NaN,NaN,NaN,NaN
2,1,2,2,30,2.0,4.0,C,22.0,J12230,NEB-24C,...,밀,임분고 21m 이상 23m미만,489.915609,4509.133733,11110185.0,홍지동,NaN,NaN,NaN,NaN
3,1,2,2,30,2.0,5.0,C,28.0,J12230,NEB-25C,...,밀,임분고 27m 이상 29m미만,451.406005,7465.346083,11110185.0,홍지동,NaN,NaN,NaN,NaN
4,1,2,2,30,2.0,5.0,C,26.0,J12230,NEB-25C,...,밀,임분고 25m 이상 27m미만,567.138239,12112.293623,11110185.0,홍지동,NaN,NaN,NaN,NaN

In [ ]:
# 필요한 컬럼만 선택

df = df[[
    'EMD_CD',
    'EMD_NM',
    'KOFTR_NM',
    'Shape_Area'
]]

df.columns = [
    'emd_cd',
    'emd_nm',
    'species',
    'area_m2'
]

In [ ]:
# 결측치 및 깨진 데이터 제거

df = df.dropna(subset=['emd_cd', 'emd_nm'])

# 숫자로 깨진 행 제거 (예: 5.18E+18)
df = df[df['emd_nm'].str.contains('[가-힣]', na=False)]

print("정제 후:", df.shape)

정제 후: (3546477, 4)

In [ ]:
# 헥타르 단위의 면적 컬럼 생성
df['area_ha'] = df['area_m2'] / 10000
df.head()

       emd_cd emd_nm species        area_m2    area_ha
0  11110103.0    궁정동   침활혼효림   26490.314701   2.649031
1  11110185.0    홍지동     소나무  112263.952659  11.226395
2  11110185.0    홍지동   기타활엽수    4509.133733   0.450913
3  11110185.0    홍지동   기타활엽수    7465.346083   0.746535
4  11110185.0    홍지동   기타활엽수   12112.293623   1.211229

In [ ]:
# 밀원수 리스트 불러오기

melliferous_df = pd.read_excel('/content/drive/MyDrive/캡스톤/밀원자원수목류_수정.xlsx')

melliferous_list = melliferous_df['밀원수명'].unique().tolist()

print("밀원수 개수:", len(melliferous_list))

밀원수 개수: 37

In [ ]:
df = df[df['species'].isin(melliferous_list)]
df.head()

         emd_cd emd_nm species       area_m2   area_ha
51   11110187.0    무악동   아까시나무  69838.923431  6.983892
170  11110183.0    평창동   아까시나무  15395.857211  1.539586
171  11110183.0    평창동   아까시나무   9836.783150  0.983678
172  11110183.0    평창동   아까시나무   2672.477864  0.267248
173  11110183.0    평창동   아까시나무   8402.919264  0.840292

In [ ]:
acacia_df = df[df['species'] == '아까시나무']
display(acacia_df.head())

         emd_cd emd_nm species       area_m2   area_ha
51   11110187.0    무악동   아까시나무  69838.923431  6.983892
170  11110183.0    평창동   아까시나무  15395.857211  1.539586
171  11110183.0    평창동   아까시나무   9836.783150  0.983678
172  11110183.0    평창동   아까시나무   2672.477864  0.267248
173  11110183.0    평창동   아까시나무   8402.919264  0.840292

In [ ]:
df

             emd_cd emd_nm species       area_m2   area_ha
51       11110187.0    무악동   아까시나무  69838.923431  6.983892
170      11110183.0    평창동   아까시나무  15395.857211  1.539586
171      11110183.0    평창동   아까시나무   9836.783150  0.983678
172      11110183.0    평창동   아까시나무   2672.477864  0.267248
173      11110183.0    평창동   아까시나무   8402.919264  0.840292
...             ...    ...     ...           ...       ...
3547249    51830310     서면     밤나무   3598.892301  0.359889
3547565    51830310     서면   아까시나무   3124.150689  0.312415
3547624    51830310     서면     밤나무  21399.060615  2.139906
3547750    51830310     서면   아까시나무   6514.302706  0.651430
3547751    51830310     서면   아까시나무   1703.108672  0.170311

[92931 rows x 5 columns]

In [ ]:
# 법정동 코드로 시도, 시군구 컬럼 추가
law = pd.read_csv('/content/drive/MyDrive/캡스톤/법정동코드 전체자료.txt', sep='\t', encoding='cp949')
law.columns = ['code', 'name', 'status']
law = law[law['status'] == '존재']

law['code'] = law['code'].astype(str).str.zfill(8)

law['sido_cd'] = law['code'].str[:2]
law['sigungu_cd'] = law['code'].str[:5]

law['sido'] = law['name'].str.split().str[0]
law['sigungu'] = law['name'].str.split().str[1]

sido = law[['sido_cd', 'sido']].drop_duplicates()
sigungu = law[['sigungu_cd', 'sigungu']].drop_duplicates()

df['emd_cd'] = df['emd_cd'].astype(str).str.zfill(8)
df['sido_cd'] = df['emd_cd'].str[:2]
df['sigungu_cd'] = df['emd_cd'].str[:5]

df = df.merge(sido, on='sido_cd', how='left')
df = df.merge(sigungu, on='sigungu_cd', how='left')

In [ ]:
df.head()

,emd_cd,emd_nm,species,area_m2,area_ha,sido_cd,sigungu_cd,sido,sigungu
0,11110187.0,무악동,아까시나무,69838.923431,6.983892,11,11110,서울특별시,종로구
1,11110183.0,평창동,아까시나무,15395.857211,1.539586,11,11110,서울특별시,종로구
2,11110183.0,평창동,아까시나무,9836.783150,0.983678,11,11110,서울특별시,종로구
3,11110183.0,평창동,아까시나무,2672.477864,0.267248,11,11110,서울특별시,종로구
4,11110183.0,평창동,아까시나무,8402.919264,0.840292,11,11110,서울특별시,종로구

In [ ]:
# 컬럼명 변경
df = df.rename(columns={'emd_nm':'emd'})

df.head()

,emd_cd,emd,species,area_m2,area_ha,sido_cd,sigungu_cd,sido,sigungu
0,11110187.0,무악동,아까시나무,69838.923431,6.983892,11,11110,서울특별시,종로구
1,11110183.0,평창동,아까시나무,15395.857211,1.539586,11,11110,서울특별시,종로구
2,11110183.0,평창동,아까시나무,9836.783150,0.983678,11,11110,서울특별시,종로구
3,11110183.0,평창동,아까시나무,2672.477864,0.267248,11,11110,서울특별시,종로구
4,11110183.0,평창동,아까시나무,8402.919264,0.840292,11,11110,서울특별시,종로구

In [ ]:
# 컬럼 순서 재배열
df = df[[
    'sido',
    'sigungu',
    'emd',
    'sido_cd',
    'sigungu_cd',
    'emd_cd',
    'species',
    'area_m2',
    'area_ha'
]]

df.head()

,sido,sigungu,emd,sido_cd,sigungu_cd,emd_cd,species,area_m2,area_ha
0,서울특별시,종로구,무악동,11,11110,11110187.0,아까시나무,69838.923431,6.983892
1,서울특별시,종로구,평창동,11,11110,11110183.0,아까시나무,15395.857211,1.539586
2,서울특별시,종로구,평창동,11,11110,11110183.0,아까시나무,9836.783150,0.983678
3,서울특별시,종로구,평창동,11,11110,11110183.0,아까시나무,2672.477864,0.267248
4,서울특별시,종로구,평창동,11,11110,11110183.0,아까시나무,8402.919264,0.840292

In [ ]:
df = df.sort_values(['sido', 'sigungu', 'emd'])
df.head()

,sido,sigungu,emd,sido_cd,sigungu_cd,emd_cd,species,area_m2,area_ha
115824,강원특별자치도,강릉시,강동면,51,51150,51150340,밤나무,5497.915743,0.549792
115825,강원특별자치도,강릉시,강동면,51,51150,51150340,밤나무,3339.467073,0.333947
115826,강원특별자치도,강릉시,강동면,51,51150,51150340,밤나무,9785.651526,0.978565
115827,강원특별자치도,강릉시,강동면,51,51150,51150340,밤나무,2925.998970,0.292600
115828,강원특별자치도,강릉시,강동면,51,51150,51150340,밤나무,1949.868685,0.194987

In [ ]:
df.dtypes

sido           object
sigungu        object
emd            object
sido_cd        object
sigungu_cd     object
emd_cd         object
species        object
area_m2       float64
area_ha       float64
dtype: object

In [ ]:
df.shape

(119199, 9)

In [ ]:
df.to_csv('/content/밀원수임상도_전처리.csv', index=False, encoding='utf-8-sig')