<a href="https://colab.research.google.com/github/yuzxin/Capstone/blob/main/%EC%82%B0%EB%A6%BC%EC%9E%90%EC%9B%90_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 산림청 - 산림자원조성사업수종정보 데이터세트 전처리 코드

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import requests # Add requests library for API calls

# 그래프 이미지 저장 폴더 생성
os.makedirs("asos_visualization", exist_ok=True)

# 한글 폰트 설정
!sudo apt-get -qq install fonts-nanum

import matplotlib.font_manager as fm

font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)

plt.rc("font", family="NanumGothic")
plt.rcParams["axes.unicode_minus"] = False

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/캡스톤/산림청_산림자원조성사업수종정보_20230131.csv',
    encoding='cp949',
    low_memory=False
)

df.head()

,활착본수,계획본수,기관명,사유림산림사업번호,용역사업계약구분,필지고유번호(PNU),산림자원조성관리사업구분,임산물종류명,본수,조성면적(제곱미터)
0,0.0,0.0,서울특별시 종로구,300008308201400003,시공용역,1111018700200030012,조림/갱신,화살나무,1600.0,0.0
1,0.0,0.0,서울특별시 종로구,300008308201400003,시공용역,1111018700200030012,조림/갱신,때죽나무,10.0,0.0
2,0.0,0.0,서울특별시 종로구,300008308201400003,시공용역,1111018700200030012,조림/갱신,활엽수기타,4000.0,0.0
3,0.0,0.0,서울특별시 종로구,300008308201400003,시공용역,1111018700200030012,조림/갱신,활엽수기타,45.0,0.0
4,0.0,0.0,서울특별시 종로구,300008308201400004,시공용역,1111011500200010024,조림/갱신,복자기나무,40.0,0.0

In [ ]:
# 데이터 크기
df.shape

(126621, 10)

In [ ]:
# 컬럼별 정보
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126621 entries, 0 to 126620
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   활착본수          79000 non-null   float64
 1   계획본수          48728 non-null   float64
 2   기관명           126621 non-null  object
 3   사유림산림사업번호     126621 non-null  int64
 4   용역사업계약구분      126621 non-null  object
 5   필지고유번호(PNU)   126621 non-null  object
 6   산림자원조성관리사업구분  126453 non-null  object
 7   임산물종류명        126428 non-null  object
 8   본수            123994 non-null  float64
 9   조성면적(제곱미터)    123976 non-null  float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.7+ MB

In [ ]:
# 기초 통계량
df.describe()

                활착본수          계획본수     사유림산림사업번호            본수    조성면적(제곱미터)
count   79000.000000  48728.000000  1.266210e+05  1.239940e+05  1.239760e+05
mean     1572.613582      5.528033  4.768552e+17  3.506926e+03  6.451496e+05
std      4260.942539    267.733580  5.367776e+16  8.291308e+04  2.062755e+07
min         0.000000      0.000000  3.000083e+17  0.000000e+00  0.000000e+00
25%         0.000000      0.000000  4.430126e+17  1.890000e+02  2.000000e+03
50%         1.000000      0.000000  4.760075e+17  1.395000e+03  8.400000e+03
75%      1416.000000      0.000000  5.060111e+17  3.900000e+03  2.000000e+04
max    204000.000000  45000.000000  9.999999e+17  2.019033e+07  4.000000e+09

In [ ]:
# 중복 데이터 개수 확인
df.duplicated().sum()

np.int64(235)

In [ ]:
# 결측치 개수 확인
df.isnull().sum()

활착본수            47621
계획본수            77893
기관명                 0
사유림산림사업번호           0
용역사업계약구분            0
필지고유번호(PNU)         0
산림자원조성관리사업구분      168
임산물종류명            193
본수               2627
조성면적(제곱미터)       2645
dtype: int64

In [ ]:
# 데이터 정제:'활착본수'가 0이거나 null인 행 제거
# '활착본수' 열의 null 값 제거
df_cleaned = df.dropna(subset=['활착본수'])

# '활착본수'가 0인 행 제거
df_cleaned = df_cleaned[df_cleaned['활착본수'] != 0]

print(f"원본 데이터프레임 크기: {df.shape}")
print(f"'활착본수'가 0이거나 null인 행 제거 후 데이터프레임 크기: {df_cleaned.shape}")

display(df_cleaned.head())

원본 데이터프레임 크기: (126621, 10)
'활착본수'가 0이거나 null인 행 제거 후 데이터프레임 크기: (39644, 10)

,활착본수,계획본수,기관명,사유림산림사업번호,용역사업계약구분,필지고유번호(PNU),산림자원조성관리사업구분,임산물종류명,본수,조성면적(제곱미터)
15,320.0,NaN,경기도 의정부시,382014208201600001,시공용역,4115010600201000035,조림/갱신,벚나무(산벚),320.0,5000.0
16,1950.0,NaN,경기도 여주시,570003808201500001,시공용역,4167035031200620001,조림/갱신,잣나무,1950.0,13000.0
17,1200.0,NaN,경기도 여주시,570003808201500001,시공용역,4167033031200130000,조림/갱신,백합나무,1200.0,4000.0
18,3000.0,NaN,경기도 여주시,570003808201500001,시공용역,4167033031200130000,조림/갱신,소나무,3000.0,10000.0
19,6900.0,NaN,경기도 여주시,570003808201500001,시공용역,4167033030200490002,조림/갱신,백합나무,6900.0,23000.0

In [ ]:
# 결측치 개수 확인
df_cleaned.isnull().sum()

활착본수                0
계획본수            21465
기관명                 0
사유림산림사업번호           0
용역사업계약구분            0
필지고유번호(PNU)         0
산림자원조성관리사업구분        0
임산물종류명              6
본수                  0
조성면적(제곱미터)          0
dtype: int64

In [ ]:
# '임산물종류명' 열의 null 값 제거
print(f"원본 데이터프레임 크기: {df_cleaned.shape}")

df_cleaned = df_cleaned.dropna(subset=['임산물종류명'])

print(f"'임산물종류명'이 null인 행 제거 후 데이터프레임 크기: {df_cleaned.shape}")

원본 데이터프레임 크기: (39644, 10)
'임산물종류명'이 null인 행 제거 후 데이터프레임 크기: (39638, 10)

In [ ]:
# 결측치 개수 확인
df_cleaned.isnull().sum()

활착본수                0
계획본수            21465
기관명                 0
사유림산림사업번호           0
용역사업계약구분            0
필지고유번호(PNU)         0
산림자원조성관리사업구분        0
임산물종류명              0
본수                  0
조성면적(제곱미터)          0
dtype: int64

In [ ]:
# 컬럼별 데이터 타입 확인
df.dtypes

활착본수            float64
계획본수            float64
기관명              object
사유림산림사업번호         int64
용역사업계약구분         object
필지고유번호(PNU)      object
산림자원조성관리사업구분     object
임산물종류명           object
본수              float64
조성면적(제곱미터)      float64
dtype: object

In [ ]:
# 활착본수, 본수, 조성면적(제곱미터) 컬럼을 정수형으로 변환
# 현재 데이터에 null 값이 없고, 소수점 이하가 의미 없는 본수/면적 데이터이므로 int64로 변환
df_cleaned['활착본수'] = df_cleaned['활착본수'].astype('int64')
df_cleaned['본수'] = df_cleaned['본수'].astype('int64')
df_cleaned['조성면적(제곱미터)'] = df_cleaned['조성면적(제곱미터)'].astype('int64')

print("\n데이터 타입 변경 후:")
display(df_cleaned.dtypes)
display(df_cleaned.head())
display(df_cleaned.describe())

데이터 타입 변경 후:

활착본수              int64
계획본수            float64
기관명              object
사유림산림사업번호         int64
용역사업계약구분         object
필지고유번호(PNU)      object
산림자원조성관리사업구분     object
임산물종류명           object
본수                int64
조성면적(제곱미터)        int64
dtype: object

,활착본수,계획본수,기관명,사유림산림사업번호,용역사업계약구분,필지고유번호(PNU),산림자원조성관리사업구분,임산물종류명,본수,조성면적(제곱미터)
15,320,NaN,경기도 의정부시,382014208201600001,시공용역,4115010600201000035,조림/갱신,벚나무(산벚),320,5000
16,1950,NaN,경기도 여주시,570003808201500001,시공용역,4167035031200620001,조림/갱신,잣나무,1950,13000
17,1200,NaN,경기도 여주시,570003808201500001,시공용역,4167033031200130000,조림/갱신,백합나무,1200,4000
18,3000,NaN,경기도 여주시,570003808201500001,시공용역,4167033031200130000,조림/갱신,소나무,3000,10000
19,6900,NaN,경기도 여주시,570003808201500001,시공용역,4167033030200490002,조림/갱신,백합나무,6900,23000

                활착본수     계획본수     사유림산림사업번호            본수     조성면적(제곱미터)
count   39638.000000  18173.0  3.963800e+04  3.963800e+04   39638.000000
mean     3134.139689      0.0  4.731931e+17  3.739906e+03   14897.577300
std      5593.852889      0.0  5.157949e+16  1.015445e+05   22697.454203
min         1.000000      0.0  3.000083e+17  1.000000e+00       0.000000
25%       220.000000      0.0  4.330083e+17  2.280000e+02    2100.000000
50%      1400.000000      0.0  4.750073e+17  1.500000e+03    8900.000000
75%      3990.000000      0.0  4.990135e+17  4.080000e+03   20000.000000
max    204000.000000      0.0  6.520184e+17  2.019033e+07  923818.000000

In [ ]:
# '조성면적(제곱미터)'가 0인 행 제거
print(f"원본 데이터프레임 크기: {df_cleaned.shape}")

df_cleaned = df_cleaned[df_cleaned['조성면적(제곱미터)'] != 0]

print(f"'임산물종류명'이 null인 행 제거 후 데이터프레임 크기: {df_cleaned.shape}")
display(df_cleaned.describe())

원본 데이터프레임 크기: (39638, 10)
'임산물종류명'이 null인 행 제거 후 데이터프레임 크기: (39550, 10)

                활착본수     계획본수     사유림산림사업번호            본수     조성면적(제곱미터)
count   39550.000000  18147.0  3.955000e+04  3.955000e+04   39550.000000
mean     3140.316662      0.0  4.733539e+17  3.747399e+03   14930.724880
std      5598.404857      0.0  5.135281e+16  1.016573e+05   22711.798822
min         1.000000      0.0  3.000083e+17  1.000000e+00       1.000000
25%       221.000000      0.0  4.330083e+17  2.310000e+02    2172.250000
50%      1410.000000      0.0  4.750073e+17  1.500000e+03    9000.000000
75%      4000.000000      0.0  4.990135e+17  4.100000e+03   20000.000000
max    204000.000000      0.0  6.520184e+17  2.019033e+07  923818.000000

In [ ]:
# '계획본수, 사유림산림사업번호, 용역사업계약구분, 산림자원조성관리사업구분'  컬럼 삭제
df_cleaned = df_cleaned.drop(columns=['계획본수', '사유림산림사업번호', '용역사업계약구분', '산림자원조성관리사업구분'])
df_cleaned.head()

    활착본수       기관명          필지고유번호(PNU)   임산물종류명    본수  조성면적(제곱미터)
15   320  경기도 의정부시  4115010600201000035  벚나무(산벚)   320        5000
16  1950   경기도 여주시  4167035031200620001      잣나무  1950       13000
17  1200   경기도 여주시  4167033031200130000     백합나무  1200        4000
18  3000   경기도 여주시  4167033031200130000      소나무  3000       10000
19  6900   경기도 여주시  4167033030200490002     백합나무  6900       23000

In [ ]:
# 컬럼명 변경
df_cleaned = df_cleaned.rename(columns={
    '활착본수': 'settle_trees',
    '기관명': 'location',
    '필지고유번호(PNU)': 'pnu',
    '임산물종류명': 'tree_species',
    '본수': 'planted_trees',
    '조성면적(제곱미터)': 'planted_area_sqm'
})

df_cleaned.head()

,settle_trees,location,pnu,tree_species,planted_trees,planted_area_sqm
15,320,경기도 의정부시,4115010600201000035,벚나무(산벚),320,5000
16,1950,경기도 여주시,4167035031200620001,잣나무,1950,13000
17,1200,경기도 여주시,4167033031200130000,백합나무,1200,4000
18,3000,경기도 여주시,4167033031200130000,소나무,3000,10000
19,6900,경기도 여주시,4167033030200490002,백합나무,6900,23000

In [ ]:
df_cleaned[['sido', 'sigungu']] = df_cleaned['location'].str.split(' ', n=1, expand=True)
df_cleaned.head()

,settle_trees,location,pnu,tree_species,planted_trees,planted_area_sqm,sido,sigungu
15,320,경기도 의정부시,4115010600201000035,벚나무(산벚),320,5000,경기도,의정부시
16,1950,경기도 여주시,4167035031200620001,잣나무,1950,13000,경기도,여주시
17,1200,경기도 여주시,4167033031200130000,백합나무,1200,4000,경기도,여주시
18,3000,경기도 여주시,4167033031200130000,소나무,3000,10000,경기도,여주시
19,6900,경기도 여주시,4167033030200490002,백합나무,6900,23000,경기도,여주시

In [ ]:
# location 컬럼 삭제
df_cleaned = df_cleaned.drop(columns=['location'])
df_cleaned.head()

,settle_trees,pnu,tree_species,planted_trees,planted_area_sqm,sido,sigungu
15,320,4115010600201000035,벚나무(산벚),320,5000,경기도,의정부시
16,1950,4167035031200620001,잣나무,1950,13000,경기도,여주시
17,1200,4167033031200130000,백합나무,1200,4000,경기도,여주시
18,3000,4167033031200130000,소나무,3000,10000,경기도,여주시
19,6900,4167033030200490002,백합나무,6900,23000,경기도,여주시

In [ ]:
# 컬럼 순서 재배열
df_cleaned = df_cleaned[[
    'sido',
    'sigungu',
    'pnu',
    'tree_species',
    'planted_trees',
    'settle_trees',
    'planted_area_sqm'
]]

display(df_cleaned.head())

,sido,sigungu,pnu,tree_species,planted_trees,settle_trees,planted_area_sqm
15,경기도,의정부시,4115010600201000035,벚나무(산벚),320,320,5000
16,경기도,여주시,4167035031200620001,잣나무,1950,1950,13000
17,경기도,여주시,4167033031200130000,백합나무,1200,1200,4000
18,경기도,여주시,4167033031200130000,소나무,3000,3000,10000
19,경기도,여주시,4167033030200490002,백합나무,6900,6900,23000

In [ ]:
bee = pd.read_excel('/content/drive/MyDrive/캡스톤/밀원자원수목류.xlsx')
bee.head()

   자원종류   밀원수명
0  목재자원  아까시나무
1  목재자원   백합나무
2  목재자원   찰피나무
3  목재자원    피나무
4  소득자원   매실나무

In [ ]:
# 밀원수 리스트
bee_trees = bee['밀원수명'].dropna().unique()
bee_trees

array(['아까시나무', '백합나무', '찰피나무', '피나무', '매실나무', '보리수나무', '마가목', '헛개나무',
       '쉬나무', '황칠나무', '신나무', '밤나무', '감나무', '동백나무', '명자나무', '등나무', '칠엽수',
       '이나무', '꽝꽝나무', '광나무', '쥐똥나무', '아왜나무', '모감주나무', '머귀나무', '칠자화',
       '벚나무(왕벚)', '벚나무(산벚)', '산딸나무', '때죽나무', '먼나무', '비쭈기나무', '좀목형',
       '뽕잎피나무', '회화나무', '족제비싸리', '싸리', '붉나무', '송악'], dtype=object)

In [ ]:
# 밀원수만 필터링
forest_bee = df_cleaned[df_cleaned['tree_species'].isin(bee_trees)]
forest_bee.head()

,sido,sigungu,pnu,tree_species,planted_trees,settle_trees,planted_area_sqm
15,경기도,의정부시,4115010600201000035,벚나무(산벚),320,320,5000
17,경기도,여주시,4167033031200130000,백합나무,1200,1200,4000
19,경기도,여주시,4167033030200490002,백합나무,6900,6900,23000
21,경기도,여주시,4167032030200460003,백합나무,3000,3000,10000
23,경기도,여주시,4167032027200130001,백합나무,1500,1500,5000

In [ ]:
forest_bee.shape

(8116, 7)

In [ ]:
forest_bee.describe()

       planted_trees   settle_trees  planted_area_sqm
count    8116.000000    8116.000000       8116.000000
mean     2571.085880    2530.726713      13042.591301
std      5151.159771    5507.547569      21032.099841
min         1.000000       1.000000          1.000000
25%       117.000000     112.000000       1729.500000
50%      1000.000000     960.000000       7000.000000
75%      3000.000000    3000.000000      17000.000000
max    172896.000000  204000.000000     563578.000000

In [ ]:
forest_bee

,sido,sigungu,pnu,tree_species,planted_trees,settle_trees,planted_area_sqm
15,경기도,의정부시,4115010600201000035,벚나무(산벚),320,320,5000
17,경기도,여주시,4167033031200130000,백합나무,1200,1200,4000
19,경기도,여주시,4167033030200490002,백합나무,6900,6900,23000
21,경기도,여주시,4167032030200460003,백합나무,3000,3000,10000
23,경기도,여주시,4167032027200130001,백합나무,1500,1500,5000
...,...,...,...,...,...,...,...
126489,전라북도,임실군,4575034031200060000,백합나무,4860,4860,24300
126538,전라북도,임실군,4575025028201340000,백합나무,1000,1000,5000
126616,충청북도,증평군,4374525040200800001,백합나무,1280,1280,6400
126617,충청북도,증평군,4374525029200150000,백합나무,4740,4740,23700
126618,충청북도,증평군,4374525029200180000,백합나무,660,660,3300

In [ ]:
# forest_bee 데이터프레임을 CSV 파일로 저장 (UTF-8-sig 인코딩 사용)
forest_bee.to_csv('산림자원_전처리.csv', index=False, encoding='utf-8-sig')
print('산림자원_전처리.csv 파일이 성공적으로 UTF-8-sig 인코딩으로 저장되었습니다.')

산림자원_전처리.csv 파일이 성공적으로 UTF-8-sig 인코딩으로 저장되었습니다.